---
title: "Benchmarks_RandomForest"
author: "Maciej Nasinski"
date: "`r Sys.Date()`"
output: 
  html_document: 
    ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(engine.path = list(python = reticulate::eng_python))
library(ranger)
library(randomForest)
library(reticulate)
library(ggplot2)
library(dplyr)
library(tidyr)
library(forcats)
set.seed(12345)
```


```{r, include = T}
iters=30L
n_trees = 30
dims = cbind(c(10L**4,10L**1),c(10L**3,10L**2),c(10L**4,5*10L**1),c(10L**4,10L**2))
mode(dims) = "integer"
nams =   sapply(1:ncol(dims),function(i) paste0("dims",paste0(dims[,i],collapse="_")))
```

```{r}
time_R_RF = list(randomForest_pure=matrix(NA,iters,ncol(dims)),
                 ranger=matrix(NA,iters,ncol(dims))
                  )

RF_models = list(
                 expression(randomForest(y=Y0,x=X0,ntree=100, mtry = floor(sqrt(N_col)))),
                 expression(ranger(x=X0,y=Y0,num.trees=100, mtry = floor(sqrt(N_col)))))

for(m in 1:length(time_R_RF)){
colnames(time_R_RF[[m]]) = nams
for(i in 1:ncol(dims)){
mat=matrix(rnorm(prod(dims[,i])),dims[1,i],dims[2,i])
colnames(mat) <- as.character(1:1000)[1:dims[2,i]]
N_col = dims[2,i] - 1
X0=mat[,-1]
Y0=mat[,1]
for(a in 1:iters){
print(a)
start=microbenchmark::get_nanotime()
R_RF = eval(RF_models[[m]])
end=microbenchmark::get_nanotime()
time_R_RF[[m]][a,i] = (end-start)/10**9
}
}

}
```

```{python}
import numpy as np
from sklearn.ensemble import RandomForestRegressor
import time
np.random.seed(12345)
dims = r.dims
iters= r.iters
time_pyn_RF = [np.zeros([iters,dims.shape[1]])]
for m in range(len(time_pyn_RF)):
  for a in range(dims.shape[1]):
    mat = np.random.randn(dims[1,a],dims[0,a])
    X = np.transpose(mat[1:])
    y = np.transpose(mat[0])
    if m==0:
      for i in range(iters):
        start = time.time()
        regr = RandomForestRegressor(n_jobs=4,n_estimators=100,max_features='sqrt')
        regr.fit(X,y)
        end = time.time()
        time_pyn_RF[0][i,a] = end-start
```


## Random Forest - Regression

Environment: R 3.6.3 i7 6700HQ 24G DDR4 2133

```{r,message=FALSE}
time_pyn_RF=py$time_pyn_RF
colnames(time_pyn_RF[[1]])=nams

res = rbind(data.frame(time_R_RF[[1]],env="randomForest"),
            data.frame(time_R_RF[[2]],env="ranger"),
            data.frame(time_pyn_RF[[1]],env="sklearn")) 
dat = res %>% gather(key,time_sec,-env) %>% mutate(key = fct_reorder(factor(key),time_sec))

gg1 = ggplot(dat,aes(y=time_sec,x=env,fill=env,col=env)) + 
  geom_violin() + 
  facet_wrap(~key,scales = "free",ncol=2)+
  theme(axis.text.x = element_blank()) +
  ggtitle("Random Forest Regression time in seconds -dimsrows_columns- 100 samples\nmtry=sqrt(Ncol) and ntree=100")
  
gg1
```

```{r}
ggsave("~/Desktop/own_R_packages/RPbenchmarks/png/RF_reg.png",gg1)
```


```{r}
for(m in 1:length(time_R_RF)){
colnames(time_R_RF[[m]]) = nams
for(i in 1:ncol(dims)){
mat=matrix(rnorm(prod(dims[,i])),dims[1,i],dims[2,i])
colnames(mat) <- as.character(1:1000)[1:dims[2,i]]
N_col = dims[2,i] - 1
X0=mat[,-1]
Y0=factor(floor(pnorm(mat[,1])*10))
for(a in 1:iters){
start=microbenchmark::get_nanotime()
R_RF = eval(RF_models[[m]])
end=microbenchmark::get_nanotime()
time_R_RF[[m]][a,i] = (end-start)/10**9
}
}
}
```

```{python}
from scipy.stats import norm
from sklearn.ensemble import RandomForestClassifier
time_pyn_RF = [np.zeros([iters,dims.shape[1]])]
for m in range(len(time_pyn_RF)):
  for a in range(dims.shape[1]):
    mat = np.random.randn(dims[1,a],dims[0,a])
    X = np.transpose(mat[1:])
    y = np.floor(norm.cdf(np.transpose(mat[0]))*10)
    if m==0:
      for i in range(iters):
        start = time.time()
        regr = RandomForestClassifier(n_jobs=4,n_estimators=100,max_features='sqrt')
        regr.fit(X,y)
        end = time.time()
        time_pyn_RF[0][i,a] = end-start
```


## Random Forest - Classification

Environment: R 3.6.3 i7 6700HQ 24G DDR4 2133

```{r,message=FALSE}
time_pyn_RF=py$time_pyn_RF
colnames(time_pyn_RF[[1]])=nams

res = rbind(data.frame(time_R_RF[[1]],env="randomForest"),
            data.frame(time_R_RF[[2]],env="ranger"),
            data.frame(time_pyn_RF[[1]],env="sklearn")) 
dat = res %>% gather(key,time_sec,-env) %>% mutate(key = fct_reorder(factor(key),time_sec))

gg1 = ggplot(dat,aes(y=time_sec,x=env,fill=env,col=env)) + 
  geom_violin() + 
  facet_wrap(~key,scales = "free",ncol=2)+
  theme(axis.text.x = element_blank()) +
  ggtitle("Random Forest Classification time in seconds - dims rows_columns - 100 samples\nmtry=sqrt(N) and ntree=100")
  
gg1
```

```{r}
ggsave("~/Desktop/own_R_packages/RPbenchmarks/png/RF_clas.png",gg1)
```

