---
title: "Benchmarks Algebra"
author: "Maciej Nasinski"
date: "`r Sys.Date()`"
output: 
  html_document: 
    ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(engine.path = list(python = reticulate::eng_python))
library(reticulate)
library(ggplot2)
library(dplyr)
library(tidyr)
library(forcats)
library(microbenchmark)
options(scipen = 999)
set.seed(12345)
```


```{r,include=T}
iters=100L
dims = cbind(c(10L**3,10L**3),c(10L**4,10L**3),c(10L**5,10L**2),c(10L**6,10L**2))
storage.mode(dims) = "integer"
nams =   sapply(1:ncol(dims),function(i) paste0("dims",paste0(dims[,i],collapse="_")))
```

```{r}
time_R_XX = matrix(NA,iters,ncol(dims))
colnames(time_R_XX) = nams
for(i in 1:ncol(dims)){
X0 = array(rnorm(prod(dims[,i])),dims[,i])
for(a in 1:iters){
start=microbenchmark::get_nanotime()
R_XX=crossprod(X0)  
end=microbenchmark::get_nanotime()
time_R_XX[a,i] = (end-start)/10**9
}
}
```


```{python}
import numpy as np
import time
np.random.seed(12345)
dims = r.dims
iters= r.iters
time_pyn_XX = np.zeros([iters,dims.shape[1]])
for a in range(dims.shape[1]):
  X0 = np.random.randn(dims[0,a],dims[1,a])
  for i in range(iters):
    start = time.time()
    model = np.matmul(np.transpose(X0),X0)
    end = time.time()
    time_pyn_XX[i,a] = end-start
```


## X'X results

Environment: R 3.6.3 i7 6700HQ 24G DDR4 2133

```{r,message=FALSE}
time_pyn_XX=py$time_pyn_XX
colnames(time_pyn_XX)=nams
res = rbind(data.frame(time_R_XX,env="R"),data.frame(time_pyn_XX,env="numpy")) 
dat = res %>% gather(key,time_sec,-env) %>% mutate(key = fct_reorder(factor(key),time_sec))

gg1 = ggplot(dat,aes(x=env,y=time_sec,fill=env,col=env)) + 
  geom_violin() + 
  facet_wrap(~key,scales = "free",ncol=2)+
  theme(axis.text.x = element_blank()) +
  ggtitle("X'X time in seconds - dims rows_columns - 100 samples")
  
gg1
```


```{r}
ggsave("~/Desktop/own_R_packages/RPbenchmarks/png/Algebra_XX.png",gg1)
```


```{r}
time_R_solve = list(
                  base_solve=matrix(NA,iters,ncol(dims)))

solve_models = list(expression(base::solve(crossprod(X0),t(X0)%*%Y0)))

for(m in 1:length(time_R_solve)){

colnames(time_R_solve[[m]]) = nams
for(i in 1:ncol(dims)){
mat = matrix(rnorm(prod(dims[,i])),dims[1,i],dims[2,i])
X0=mat[,-1]
Y0=mat[,1]
for(a in 1:iters){
start=microbenchmark::get_nanotime()
R_solve = eval(solve_models[[m]])
end=microbenchmark::get_nanotime()
time_R_solve[[m]][a,i] = (end-start)/10**9
}
}

}
```

```{python}
import numpy as np
from numpy.linalg import solve
import time
np.random.seed(1234)
dims = r.dims
iters= r.iters
time_pyn_solve = [np.zeros([iters,dims.shape[1]])]
for m in range(len(time_pyn_solve)):
  for a in range(dims.shape[1]):
    mat = np.random.randn(dims[1,a],dims[0,a])
    X = np.transpose(mat[1:])
    y = np.transpose(mat[0])
    if m==0:
      for i in range(iters):
        start = time.time()
        s = solve(np.matmul(np.transpose(X),X),np.matmul(np.transpose(X),y))
        end = time.time()
        time_pyn_solve[0][i,a] = end-start
```


## solve XB=Y

Environment: R 3.6.3 i7 6700HQ 24G DDR4 2133

```{r,message=FALSE}
time_pyn_solve=py$time_pyn_solve
colnames(time_pyn_solve[[1]])=nams

res = rbind(
            data.frame(time_R_solve[[1]],env="base::solve"),
            data.frame(time_pyn_solve[[1]],env="numpy")) 
dat = res %>% gather(key,time_sec,-env) %>% mutate(key = fct_reorder(factor(key),time_sec))

gg1 = ggplot(dat,aes(y=time_sec,x=env,fill=env,col=env)) + 
  geom_violin() + 
  facet_wrap(~key,scales = "free",ncol=2)+
  theme(axis.text.x = element_blank()) +
  ggtitle("solve time in seconds - dims rows_columns - 100 samples")
  
gg1
```

```{r}
ggsave("~/Desktop/own_R_packages/RPbenchmarks/png/solve.png",gg1)
```
